# copied from /home/adr/.m2/repository/org/springframework/cloud/spring-cloud-config-server/3.0.3/spring-cloud-config-server-3.0.3.jar!/configserver.yml
# see also https://github.com/spring-cloud-samples/configserver

info:
  component: Config Server
spring:
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/spring-cloud-samples/config-repo
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/spring-cloud-samples/config-repo

server:
  port: 8888
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
  # from https://github.com/spring-cloud-samples/configserver
  endpoint:
    env:
      post:
        enabled: true
